import httpx
from bs4 import BeautifulSoup
import asyncio
from pydantic import BaseModel

class ScrapedData(BaseModel):
    url: str
    title: str
    meta_description: str
    text_content: str
    is_fallback: bool
    error: str | None = None

async def scrape_url(url: str) -> ScrapedData:
    """
    Attempts to scrape a URL using HTTPX and BeautifulSoup.
    If it fails (e.g. rate limit, broken URL, timeout), it gracefully falls back to a synthetic response.
    """
    try:
        # We use a short timeout to fail fast for the demo
        async with httpx.AsyncClient(timeout=3.0) as client:
            response = await client.get(url, follow_redirects=True)
            response.raise_for_status()
            
            soup = BeautifulSoup(response.text, 'html.parser')
            
            title = soup.title.string if soup.title else ""
            meta_desc = ""
            if soup.find("meta", attrs={"name": "description"}):
                meta_desc = soup.find("meta", attrs={"name": "description"}).get("content", "")
                
            # Extract basic text content (limited to avoid huge payloads)
            text_content = " ".join(soup.stripped_strings)[:2000]
            
            return ScrapedData(
                url=url,
                title=title,
                meta_description=meta_desc,
                text_content=text_content,
                is_fallback=False
            )
            
    except Exception as e:
        # Fallback Mode: Graceful Failure Recovery
        print(f"Scraper failed for {url}: {e}. Entering fallback mode.")
        return get_synthetic_fallback(url, str(e))

def get_synthetic_fallback(url: str, error_msg: str) -> ScrapedData:
    """
    Generates synthetic data for known demo URLs if scraping fails or URL is invalid.
    """
    if "fashion" in url.lower() or "d2c" in url.lower():
        return ScrapedData(
            url=url,
            title="Premium Fashion D2C Brand",
            meta_description="Shop the latest trends. Powered by Shopify.",
            text_content="Welcome to our fashion store. Privacy Policy and Terms of Service available. GSTIN: 27AADCB2230M1Z2. Checkout our new collection.",
            is_fallback=True,
            error=error_msg
        )
    elif "saas" in url.lower() or "b2b" in url.lower():
         return ScrapedData(
            url=url,
            title="Enterprise B2B SaaS",
            meta_description="Automate your workflow. Pricing plans available.",
            text_content="Enterprise solutions for modern teams. Subscription plans starting at $99/mo. Contact sales for invoicing.",
            is_fallback=True,
            error=error_msg
        )
    elif "broken" in url.lower() or "invalid" in url.lower():
         # Explicitly designed broken store to test failure recovery
         return ScrapedData(
            url=url,
            title="Store Not Found / Connection Error",
            meta_description="",
            text_content="Failed to retrieve store data. The website might be down, rate-limited, or no longer exists.",
            is_fallback=True,
            error=f"Simulated or real failure: {error_msg}"
        )
    else:
        # Generic fallback
        return ScrapedData(
            url=url,
            title=f"Fallback Data for {url}",
            meta_description="Generated fallback due to scraper failure.",
            text_content="This is synthetic data generated by the RazorPulse fallback engine because the original site could not be reached.",
            is_fallback=True,
            error=error_msg
        )
